# -*- coding: utf-8 -*-
"""introducao_data_science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mW5kxQWFoA6f1MmSq3FyutG_j7n0wLyQ
"""

import pandas as pd

notas = pd.read_csv("ratings.csv")

notas.head()

notas.shape

notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

notas["nota"].mean()

notas.nota.unique()

notas.nota.value_counts()

print("Media", notas.nota.mean())
print("Mediana", notas.nota.median())